import NoteBlock from '../../../components/content/NoteBlock.jsx'
import CommandBlock from '../../../components/content/CommandBlock.jsx'

export default function S2PngMetadata() {
  return (
    <>
      <p>
        Every PNG saved by SaveImage embeds the workflow that produced it as metadata. This is the
        single most useful "how did I make this" feature in any local diffusion tool. Drag the PNG
        onto the canvas and the entire workflow restores.
      </p>

      <h2>Try it</h2>
      <ol>
        <li>Open the PNG you generated in chapter 5 from <code>~/AI/ComfyUI/output/</code>.</li>
        <li>Drag the file onto the ComfyUI canvas.</li>
        <li>The full graph loads — including widget values, group colors, sticky notes.</li>
      </ol>

      <h2>How the metadata is stored</h2>
      <p>
        ComfyUI writes two PNG <code>tEXt</code> chunks: <code>workflow</code> (the workflow JSON)
        and <code>prompt</code> (the API-format JSON). You can inspect them on the command line:
      </p>
      <CommandBlock command="exiftool ~/AI/ComfyUI/output/first-workflow_00001_.png" />
      <p>
        (Install exiftool with <code>brew install exiftool</code>.) You'll see the embedded JSON in
        the output.
      </p>

      <h2>Strip the metadata when sharing</h2>
      <p>
        When you post a generated image publicly, the embedded workflow is visible to anyone who
        downloads the PNG. That's usually fine, sometimes not. To strip:
      </p>
      <CommandBlock command="exiftool -all= -overwrite_original output.png" label="Removes all metadata" />
      <p>Or in SaveImage's settings, set <code>save_metadata</code> = false (where supported).</p>

      <NoteBlock title="JPEG and webp don't preserve workflow">
        The workflow chunk is PNG-specific. If your SaveImage variant emits JPEG/webp, the workflow
        is lost. For shareable assets — a generated reel, a thumbnail — that's usually what you want.
        For your own iteration, keep PNG and you have a built-in "edit history" for free.
      </NoteBlock>

      <h2>Workflow round-trips through PNG</h2>
      <p>
        Drag a PNG generated by someone else onto your canvas → their full workflow appears. Most of
        the time you'll be missing custom nodes (red placeholders) or models (the dropdown points to
        a file you don't have). This is how the community shares recipes — copy the PNG from a
        Reddit/Discord post, drag it in, fix the missing pieces, queue.
      </p>
    </>
  )
}
