/** Audio (music, sfx) models. Mac-friendly. */
export default [
  {
    id: 'stable-audio-open',
    name: 'Stable Audio Open 1.0',
    modality: 'audio',
    family: 'Stable Audio',
    dtype: 'fp16',
    sizeGB: 2.4,
    license: 'Stability AI Community',
    hf: 'https://huggingface.co/stabilityai/stable-audio-open-1.0',
    macRecommended: true,
    notes: 'Text-to-audio (sfx, loops, ambience). Up to 47s.',
  },
  {
    id: 'audioldm2',
    name: 'AudioLDM 2',
    modality: 'audio',
    family: 'AudioLDM',
    dtype: 'fp16',
    sizeGB: 1.6,
    license: 'CC-BY-NC-SA-4.0',
    hf: 'https://huggingface.co/cvssp/audioldm2',
    macRecommended: true,
    notes: 'Text-to-audio. Light, Mac-friendly.',
  },
  {
    id: 'musicgen-medium',
    name: 'MusicGen Medium',
    modality: 'audio',
    family: 'MusicGen',
    dtype: 'fp16',
    sizeGB: 3.0,
    license: 'CC-BY-NC-4.0',
    hf: 'https://huggingface.co/facebook/musicgen-medium',
    macRecommended: true,
    notes: 'Music generation; runs on MPS via transformers.',
  },
  {
    id: 'musicgen-large',
    name: 'MusicGen Large',
    modality: 'audio',
    family: 'MusicGen',
    dtype: 'fp16',
    sizeGB: 6.6,
    license: 'CC-BY-NC-4.0',
    hf: 'https://huggingface.co/facebook/musicgen-large',
    macRecommended: true,
    notes: 'Higher quality. ~6.6 GB; comfortable on 24 GB.',
  },
  {
    id: 'ace-step',
    name: 'ACE-Step',
    modality: 'audio',
    family: 'ACE-Step',
    dtype: 'fp16',
    sizeGB: 4.0,
    license: 'Apache 2.0',
    hf: 'https://huggingface.co/ACE-Step/ACE-Step-v1-3.5B',
    macRecommended: true,
    notes: 'Open music generation; vocals + instrumentals.',
  },
]
