/** ControlNet & spatial-conditioning models. */
export default [
  {
    id: 'cn-sdxl-canny',
    name: 'ControlNet SDXL Canny',
    modality: 'controlnet',
    family: 'ControlNet',
    dtype: 'fp16',
    sizeGB: 2.5,
    license: 'OpenRAIL',
    hf: 'https://huggingface.co/diffusers/controlnet-canny-sdxl-1.0',
    macRecommended: true,
    notes: 'Edge-guided generation for SDXL.',
  },
  {
    id: 'cn-sdxl-depth',
    name: 'ControlNet SDXL Depth',
    modality: 'controlnet',
    family: 'ControlNet',
    dtype: 'fp16',
    sizeGB: 2.5,
    license: 'OpenRAIL',
    hf: 'https://huggingface.co/diffusers/controlnet-depth-sdxl-1.0',
    macRecommended: true,
    notes: 'Depth-guided. Preserves geometry while changing style.',
  },
  {
    id: 'cn-sdxl-openpose',
    name: 'ControlNet SDXL OpenPose',
    modality: 'controlnet',
    family: 'ControlNet',
    dtype: 'fp16',
    sizeGB: 2.5,
    license: 'OpenRAIL',
    hf: 'https://huggingface.co/thibaud/controlnet-openpose-sdxl-1.0',
    macRecommended: true,
    notes: 'Pose-guided. Pair with character LoRA for clones.',
  },
  {
    id: 'cn-sdxl-union',
    name: 'ControlNet++ SDXL Union ProMax',
    modality: 'controlnet',
    family: 'ControlNet',
    dtype: 'fp16',
    sizeGB: 2.5,
    license: 'Apache 2.0',
    hf: 'https://huggingface.co/xinsir/controlnet-union-sdxl-1.0',
    macRecommended: true,
    notes: 'One model handles canny/depth/pose/lineart/etc.',
  },
  {
    id: 'cn-flux-union',
    name: 'FLUX ControlNet Union',
    modality: 'controlnet',
    family: 'ControlNet',
    dtype: 'fp16',
    sizeGB: 6.6,
    license: 'FLUX-dev Non-Commercial',
    hf: 'https://huggingface.co/InstantX/FLUX.1-dev-Controlnet-Union',
    macRecommended: true,
    notes: 'Pair with FLUX GGUF base on Mac.',
  },
  {
    id: 'cn-sd15-openpose',
    name: 'ControlNet SD1.5 OpenPose',
    modality: 'controlnet',
    family: 'ControlNet',
    dtype: 'fp16',
    sizeGB: 1.4,
    license: 'OpenRAIL',
    hf: 'https://huggingface.co/lllyasviel/ControlNet-v1-1',
    macRecommended: true,
    notes: 'Lightweight; great for fast iteration.',
  },
  {
    id: 'depth-anything-v2',
    name: 'Depth-Anything v2 (large)',
    modality: 'controlnet',
    family: 'Preprocessor',
    dtype: 'fp16',
    sizeGB: 1.3,
    license: 'CC-BY-NC-4.0',
    hf: 'https://huggingface.co/depth-anything/Depth-Anything-V2-Large',
    macRecommended: true,
    notes: 'Best monocular depth estimator. Used as ControlNet preprocessor.',
  },
  {
    id: 'dwpose',
    name: 'DWPose',
    modality: 'controlnet',
    family: 'Preprocessor',
    dtype: 'fp16',
    sizeGB: 0.4,
    license: 'Apache 2.0',
    hf: 'https://huggingface.co/yzd-v/DWPose',
    macRecommended: true,
    notes: 'Body+hands+face pose estimator.',
  },
]
