/**
 * Image-generation models. Mac-friendly entries for 24 GB unified memory.
 * Schema: { id, name, modality, family, dtype, sizeGB, license, hf, civitai, macRecommended, notes }
 */
export default [
  {
    id: 'sd15-base',
    name: 'Stable Diffusion 1.5',
    modality: 'image',
    family: 'SD1.5',
    dtype: 'fp16',
    sizeGB: 2.1,
    license: 'CreativeML OpenRAIL-M',
    hf: 'https://huggingface.co/runwayml/stable-diffusion-v1-5',
    macRecommended: true,
    notes: 'Tiny footprint. Great for fast iteration on Mac. Native 512×512.',
  },
  {
    id: 'sdxl-base',
    name: 'SDXL Base 1.0',
    modality: 'image',
    family: 'SDXL',
    dtype: 'fp16',
    sizeGB: 6.7,
    license: 'CreativeML OpenRAIL++-M',
    hf: 'https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0',
    macRecommended: true,
    notes: 'Native 1024². Comfortable on 24 GB unified memory.',
  },
  {
    id: 'sdxl-refiner',
    name: 'SDXL Refiner 1.0',
    modality: 'image',
    family: 'SDXL',
    dtype: 'fp16',
    sizeGB: 6.1,
    license: 'CreativeML OpenRAIL++-M',
    hf: 'https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0',
    macRecommended: true,
    notes: 'Optional polish pass. Skip on tight memory budget.',
  },
  {
    id: 'sdxl-lightning',
    name: 'SDXL Lightning (4-step)',
    modality: 'image',
    family: 'SDXL',
    dtype: 'fp16',
    sizeGB: 6.7,
    license: 'OpenRAIL++',
    hf: 'https://huggingface.co/ByteDance/SDXL-Lightning',
    macRecommended: true,
    notes: '4-step distillation. ~3x faster on M5 Pro than base SDXL.',
  },
  {
    id: 'pony-v6',
    name: 'Pony Diffusion v6 XL',
    modality: 'image',
    family: 'SDXL',
    dtype: 'fp16',
    sizeGB: 6.5,
    license: 'Fair AI Public License',
    civitai: 'https://civitai.com/models/257749',
    macRecommended: true,
    notes: 'Booru-tag prompting. Strong character/anime base.',
  },
  {
    id: 'illustrious-xl',
    name: 'Illustrious-XL v0.1',
    modality: 'image',
    family: 'SDXL',
    dtype: 'fp16',
    sizeGB: 6.5,
    license: 'Fair AI Public License',
    civitai: 'https://civitai.com/models/795765',
    macRecommended: true,
    notes: 'Successor to Pony for anime/illustration.',
  },
  {
    id: 'noobai-xl',
    name: 'NoobAI-XL',
    modality: 'image',
    family: 'SDXL',
    dtype: 'fp16',
    sizeGB: 6.5,
    license: 'Fair AI Public License',
    civitai: 'https://civitai.com/models/833294',
    macRecommended: true,
    notes: 'Illustrious-derived; broader style coverage.',
  },
  {
    id: 'sd35-large',
    name: 'SD 3.5 Large',
    modality: 'image',
    family: 'SD3',
    dtype: 'bf16',
    sizeGB: 16.5,
    license: 'Stability AI Community',
    hf: 'https://huggingface.co/stabilityai/stable-diffusion-3.5-large',
    macRecommended: false,
    notes: 'Use bf16 (not fp8) on MPS. T5-XXL also bf16. Tight on 24 GB.',
  },
  {
    id: 'sd35-large-turbo',
    name: 'SD 3.5 Large Turbo',
    modality: 'image',
    family: 'SD3',
    dtype: 'bf16',
    sizeGB: 16.5,
    license: 'Stability AI Community',
    hf: 'https://huggingface.co/stabilityai/stable-diffusion-3.5-large-turbo',
    macRecommended: false,
    notes: '4-step distill of 3.5 Large. Same memory budget.',
  },
  {
    id: 'sd35-medium',
    name: 'SD 3.5 Medium',
    modality: 'image',
    family: 'SD3',
    dtype: 'bf16',
    sizeGB: 5.0,
    license: 'Stability AI Community',
    hf: 'https://huggingface.co/stabilityai/stable-diffusion-3.5-medium',
    macRecommended: true,
    notes: 'Mac-friendly SD3 variant. Pair with bf16 t5-xxl.',
  },
  {
    id: 'flux-dev',
    name: 'FLUX.1 Dev (fp16)',
    modality: 'image',
    family: 'FLUX',
    dtype: 'fp16',
    sizeGB: 23.8,
    license: 'FLUX.1-dev Non-Commercial',
    hf: 'https://huggingface.co/black-forest-labs/FLUX.1-dev',
    macRecommended: false,
    notes: 'Borderline on 24 GB. Prefer GGUF Q4/Q5 on Mac.',
  },
  {
    id: 'flux-dev-gguf-q4',
    name: 'FLUX.1 Dev GGUF Q4_K_S',
    modality: 'image',
    family: 'FLUX',
    dtype: 'gguf-q4',
    sizeGB: 6.8,
    license: 'FLUX.1-dev Non-Commercial',
    hf: 'https://huggingface.co/city96/FLUX.1-dev-gguf',
    macRecommended: true,
    notes: 'The Mac-recommended FLUX. Use UnetLoaderGGUF + DualCLIPLoaderGGUF.',
  },
  {
    id: 'flux-dev-gguf-q5',
    name: 'FLUX.1 Dev GGUF Q5_K_S',
    modality: 'image',
    family: 'FLUX',
    dtype: 'gguf-q5',
    sizeGB: 8.3,
    license: 'FLUX.1-dev Non-Commercial',
    hf: 'https://huggingface.co/city96/FLUX.1-dev-gguf',
    macRecommended: true,
    notes: 'Higher quality than Q4 with modest extra memory.',
  },
  {
    id: 'flux-dev-gguf-q8',
    name: 'FLUX.1 Dev GGUF Q8_0',
    modality: 'image',
    family: 'FLUX',
    dtype: 'gguf-q8',
    sizeGB: 12.7,
    license: 'FLUX.1-dev Non-Commercial',
    hf: 'https://huggingface.co/city96/FLUX.1-dev-gguf',
    macRecommended: true,
    notes: 'Near-fp16 quality. Tight but viable on 24 GB.',
  },
  {
    id: 'flux-schnell-gguf-q5',
    name: 'FLUX.1 Schnell GGUF Q5_K_S',
    modality: 'image',
    family: 'FLUX',
    dtype: 'gguf-q5',
    sizeGB: 8.3,
    license: 'Apache 2.0',
    hf: 'https://huggingface.co/city96/FLUX.1-schnell-gguf',
    macRecommended: true,
    notes: '4-step distill. Apache-licensed. Fastest FLUX on Mac.',
  },
  {
    id: 'flux-redux',
    name: 'FLUX.1 Redux',
    modality: 'image',
    family: 'FLUX',
    dtype: 'fp16',
    sizeGB: 0.6,
    license: 'FLUX.1-dev Non-Commercial',
    hf: 'https://huggingface.co/black-forest-labs/FLUX.1-Redux-dev',
    macRecommended: true,
    notes: 'Image-prompting adapter. Pairs with FLUX Dev GGUF.',
  },
  {
    id: 'flux-fill',
    name: 'FLUX.1 Fill',
    modality: 'image',
    family: 'FLUX',
    dtype: 'gguf-q5',
    sizeGB: 8.5,
    license: 'FLUX.1-dev Non-Commercial',
    hf: 'https://huggingface.co/black-forest-labs/FLUX.1-Fill-dev',
    macRecommended: true,
    notes: 'FLUX-native inpaint. GGUF mirrors exist for Mac.',
  },
  {
    id: 'lustify',
    name: 'Lustify SDXL',
    modality: 'image',
    family: 'SDXL',
    dtype: 'fp16',
    sizeGB: 6.5,
    license: 'Fair AI Public License',
    civitai: 'https://civitai.com/models/573152',
    macRecommended: true,
    notes: 'Photoreal SDXL finetune. Adult content; local-only use.',
  },
]
