/** IP-Adapter & identity models (PuLID, InstantID, FaceID, talking-head). */
export default [
  {
    id: 'ipa-sdxl-plus',
    name: 'IP-Adapter Plus SDXL',
    modality: 'ipadapter',
    family: 'IP-Adapter',
    dtype: 'fp16',
    sizeGB: 0.85,
    license: 'Apache 2.0',
    hf: 'https://huggingface.co/h94/IP-Adapter',
    macRecommended: true,
    notes: 'Image-prompting for SDXL. Style + composition transfer.',
  },
  {
    id: 'ipa-faceid-portrait',
    name: 'IP-Adapter FaceID Portrait SDXL',
    modality: 'ipadapter',
    family: 'IP-Adapter',
    dtype: 'fp16',
    sizeGB: 0.95,
    license: 'Apache 2.0',
    hf: 'https://huggingface.co/h94/IP-Adapter-FaceID',
    macRecommended: true,
    notes: 'Identity preservation from reference face.',
  },
  {
    id: 'instantid',
    name: 'InstantID',
    modality: 'ipadapter',
    family: 'InstantID',
    dtype: 'fp16',
    sizeGB: 1.7,
    license: 'Apache 2.0',
    hf: 'https://huggingface.co/InstantX/InstantID',
    macRecommended: true,
    notes: 'Strong identity + pose. Pair with ControlNet.',
  },
  {
    id: 'pulid-flux',
    name: 'PuLID-FLUX',
    modality: 'ipadapter',
    family: 'PuLID',
    dtype: 'fp16',
    sizeGB: 1.2,
    license: 'Apache 2.0',
    hf: 'https://huggingface.co/guozinan/PuLID',
    macRecommended: true,
    notes: 'Best identity model for FLUX on Mac.',
  },
  {
    id: 'pulid-sdxl',
    name: 'PuLID for SDXL',
    modality: 'ipadapter',
    family: 'PuLID',
    dtype: 'fp16',
    sizeGB: 1.2,
    license: 'Apache 2.0',
    hf: 'https://huggingface.co/guozinan/PuLID',
    macRecommended: true,
    notes: 'Identity preservation in SDXL pipelines.',
  },
  {
    id: 'reactor',
    name: 'ReActor (face swap)',
    modality: 'ipadapter',
    family: 'Face-swap',
    dtype: 'fp16',
    sizeGB: 0.55,
    license: 'GPL-3.0',
    hf: 'https://huggingface.co/datasets/Gourieff/ReActor',
    macRecommended: true,
    notes: 'Post-hoc face swap. Use sparingly to repair identity drift.',
  },
  {
    id: 'liveportrait',
    name: 'LivePortrait',
    modality: 'ipadapter',
    family: 'Talking-head',
    dtype: 'fp16',
    sizeGB: 0.5,
    license: 'CC-BY-NC-4.0',
    hf: 'https://huggingface.co/KwaiVGI/LivePortrait',
    macRecommended: true,
    notes: 'Expression transfer for talking-head clones.',
  },
  {
    id: 'sonic',
    name: 'Sonic',
    modality: 'ipadapter',
    family: 'Talking-head',
    dtype: 'fp16',
    sizeGB: 4.5,
    license: 'CC-BY-NC-4.0',
    hf: 'https://huggingface.co/LeonJoe13/Sonic',
    macRecommended: true,
    notes: 'Audio-driven portrait animation. Slower on Mac (~7 min/clip).',
  },
  {
    id: 'hallo2',
    name: 'Hallo2',
    modality: 'ipadapter',
    family: 'Talking-head',
    dtype: 'fp16',
    sizeGB: 4.0,
    license: 'CC-BY-NC-4.0',
    hf: 'https://huggingface.co/fudan-generative-ai/hallo2',
    macRecommended: false,
    notes: 'Long-form talking-head. Heavy on 24 GB; works in chunks.',
  },
  {
    id: 'sadtalker',
    name: 'SadTalker',
    modality: 'ipadapter',
    family: 'Talking-head',
    dtype: 'fp16',
    sizeGB: 1.4,
    license: 'CC-BY-NC-4.0',
    hf: 'https://huggingface.co/vinthony/SadTalker',
    macRecommended: true,
    notes: 'Older but Mac-friendly fallback.',
  },
  {
    id: 'wav2lip',
    name: 'Wav2Lip',
    modality: 'ipadapter',
    family: 'Lip-sync',
    dtype: 'fp16',
    sizeGB: 0.5,
    license: 'BSD-3-Clause',
    hf: 'https://huggingface.co/camenduru/wav2lip',
    macRecommended: true,
    notes: 'Mouth-only lip sync overlay. Fast.',
  },
  {
    id: 'musetalk',
    name: 'MuseTalk',
    modality: 'ipadapter',
    family: 'Lip-sync',
    dtype: 'fp16',
    sizeGB: 1.6,
    license: 'CC-BY-NC-4.0',
    hf: 'https://huggingface.co/TMElyralab/MuseTalk',
    macRecommended: true,
    notes: 'Real-time lip sync for talking-head pipelines.',
  },
]
