/** Local LLMs for the agentic capstone. Mac-friendly. */
export default [
  {
    id: 'llama-31-8b-instruct',
    name: 'Llama 3.1 8B Instruct',
    modality: 'llm',
    family: 'Llama',
    dtype: 'gguf-q5',
    sizeGB: 5.7,
    license: 'Llama 3.1 Community',
    hf: 'https://huggingface.co/bartowski/Meta-Llama-3.1-8B-Instruct-GGUF',
    macRecommended: true,
    notes: 'Workhorse local LLM. Run via Ollama or llama.cpp on M5.',
  },
  {
    id: 'qwen-25-7b-instruct',
    name: 'Qwen 2.5 7B Instruct',
    modality: 'llm',
    family: 'Qwen',
    dtype: 'gguf-q5',
    sizeGB: 5.4,
    license: 'Apache 2.0',
    hf: 'https://huggingface.co/bartowski/Qwen2.5-7B-Instruct-GGUF',
    macRecommended: true,
    notes: 'Apache-licensed alternative to Llama 8B.',
  },
  {
    id: 'qwen-25-14b-instruct',
    name: 'Qwen 2.5 14B Instruct',
    modality: 'llm',
    family: 'Qwen',
    dtype: 'gguf-q5',
    sizeGB: 10.5,
    license: 'Apache 2.0',
    hf: 'https://huggingface.co/bartowski/Qwen2.5-14B-Instruct-GGUF',
    macRecommended: true,
    notes: 'Stronger reasoning. Comfortable on 24 GB alongside ComfyUI.',
  },
  {
    id: 'deepseek-r1-distill-qwen-14b',
    name: 'DeepSeek-R1-Distill-Qwen-14B',
    modality: 'llm',
    family: 'DeepSeek',
    dtype: 'gguf-q5',
    sizeGB: 10.5,
    license: 'MIT',
    hf: 'https://huggingface.co/bartowski/DeepSeek-R1-Distill-Qwen-14B-GGUF',
    macRecommended: true,
    notes: 'Reasoning-tuned. Good for the script-agent stage.',
  },
  {
    id: 'qwen2-vl-7b',
    name: 'Qwen2-VL 7B Instruct',
    modality: 'llm',
    family: 'Qwen-VL',
    dtype: 'fp16',
    sizeGB: 16.4,
    license: 'Apache 2.0',
    hf: 'https://huggingface.co/Qwen/Qwen2-VL-7B-Instruct',
    macRecommended: true,
    notes: 'Vision-language. LLM-judge for image/video review.',
  },
  {
    id: 'florence-2-large',
    name: 'Florence-2 Large',
    modality: 'llm',
    family: 'Florence',
    dtype: 'fp16',
    sizeGB: 1.6,
    license: 'MIT',
    hf: 'https://huggingface.co/microsoft/Florence-2-large',
    macRecommended: true,
    notes: 'Captioning, grounding, OCR. Tiny + fast.',
  },
  {
    id: 'wd14-tagger',
    name: 'WD14 Tagger v3',
    modality: 'llm',
    family: 'Tagger',
    dtype: 'fp16',
    sizeGB: 0.4,
    license: 'Apache 2.0',
    hf: 'https://huggingface.co/SmilingWolf/wd-eva02-large-tagger-v3',
    macRecommended: true,
    notes: 'Booru-style auto-tagging for LoRA dataset prep.',
  },
]
