/** Upscaler / restoration models. Mac-friendly. */
export default [
  {
    id: '4x-ultrasharp',
    name: '4x-UltraSharp',
    modality: 'upscaler',
    family: 'ESRGAN',
    dtype: 'fp16',
    sizeGB: 0.07,
    license: 'CC0',
    hf: 'https://huggingface.co/lokCX/4x-Ultrasharp',
    macRecommended: true,
    notes: 'Default photo upscale. Sharp without over-smoothing.',
  },
  {
    id: 'realesrgan-x4',
    name: 'RealESRGAN x4plus',
    modality: 'upscaler',
    family: 'ESRGAN',
    dtype: 'fp16',
    sizeGB: 0.07,
    license: 'BSD-3-Clause',
    hf: 'https://huggingface.co/ai-forever/Real-ESRGAN',
    macRecommended: true,
    notes: 'General-purpose realistic upscale.',
  },
  {
    id: '4x-nmkd-siax',
    name: '4x NMKD Siax',
    modality: 'upscaler',
    family: 'ESRGAN',
    dtype: 'fp16',
    sizeGB: 0.07,
    license: 'CC0',
    hf: 'https://huggingface.co/uwg/upscaler',
    macRecommended: true,
    notes: 'Photo-detail oriented; preserves skin texture.',
  },
  {
    id: 'supir',
    name: 'SUPIR',
    modality: 'upscaler',
    family: 'Diffusion-upscale',
    dtype: 'fp16',
    sizeGB: 11.5,
    license: 'Non-commercial',
    hf: 'https://huggingface.co/Kijai/SUPIR_pruned',
    macRecommended: false,
    notes: 'Diffusion-based upscale. Quality is exceptional, memory is heavy.',
  },
  {
    id: 'gfpgan-v14',
    name: 'GFPGAN v1.4',
    modality: 'upscaler',
    family: 'Face restoration',
    dtype: 'fp16',
    sizeGB: 0.34,
    license: 'Apache 2.0',
    hf: 'https://huggingface.co/leonelhs/gfpgan',
    macRecommended: true,
    notes: 'Classic face restorer. Pair with ESRGAN for photos.',
  },
  {
    id: 'codeformer',
    name: 'CodeFormer',
    modality: 'upscaler',
    family: 'Face restoration',
    dtype: 'fp16',
    sizeGB: 0.36,
    license: 'NTU S-Lab License 1.0',
    hf: 'https://huggingface.co/sczhou/CodeFormer',
    macRecommended: true,
    notes: 'Identity-preserving face fix.',
  },
]
