/**
 * Video models. Mac-friendly entries for 24 GB unified memory.
 */
export default [
  {
    id: 'ltx-video-097',
    name: 'LTX-Video 0.9.7',
    modality: 'video',
    family: 'LTX-Video',
    dtype: 'bf16',
    sizeGB: 18.0,
    license: 'OpenRAIL-M',
    hf: 'https://huggingface.co/Lightricks/LTX-Video',
    macRecommended: true,
    notes: 'Best video model for 24 GB Macs. Native 768×512.',
  },
  {
    id: 'ltx-video-13b',
    name: 'LTX-Video 13B',
    modality: 'video',
    family: 'LTX-Video',
    dtype: 'gguf-q5',
    sizeGB: 9.0,
    license: 'OpenRAIL-M',
    hf: 'https://huggingface.co/Lightricks/LTX-Video',
    macRecommended: true,
    notes: 'Higher fidelity. Use GGUF on Mac.',
  },
  {
    id: 'hunyuan-video-gguf-q4',
    name: 'HunyuanVideo GGUF Q4_K_S',
    modality: 'video',
    family: 'HunyuanVideo',
    dtype: 'gguf-q4',
    sizeGB: 8.5,
    license: 'Tencent Hunyuan Community',
    hf: 'https://huggingface.co/city96/HunyuanVideo-gguf',
    macRecommended: true,
    notes: '13B DiT. Slow on Mac (~10–20 min for 5s clips) but viable.',
  },
  {
    id: 'hunyuan-video-gguf-q5',
    name: 'HunyuanVideo GGUF Q5_K_S',
    modality: 'video',
    family: 'HunyuanVideo',
    dtype: 'gguf-q5',
    sizeGB: 10.5,
    license: 'Tencent Hunyuan Community',
    hf: 'https://huggingface.co/city96/HunyuanVideo-gguf',
    macRecommended: true,
    notes: 'Higher quality Hunyuan; tight on 24 GB.',
  },
  {
    id: 'wan-22-5b-i2v',
    name: 'Wan 2.2 5B I2V',
    modality: 'video',
    family: 'Wan',
    dtype: 'bf16',
    sizeGB: 11.0,
    license: 'Apache 2.0',
    hf: 'https://huggingface.co/Wan-AI/Wan2.2-I2V-A5B',
    macRecommended: true,
    notes: 'Faster Mac variant. Image-to-video.',
  },
  {
    id: 'wan-22-14b-gguf',
    name: 'Wan 2.2 14B GGUF Q5',
    modality: 'video',
    family: 'Wan',
    dtype: 'gguf-q5',
    sizeGB: 11.0,
    license: 'Apache 2.0',
    hf: 'https://huggingface.co/city96/Wan2.2-T2V-A14B-gguf',
    macRecommended: true,
    notes: 'Higher quality 14B. GGUF needed on 24 GB.',
  },
  {
    id: 'wan-vace',
    name: 'Wan VACE',
    modality: 'video',
    family: 'Wan',
    dtype: 'gguf-q5',
    sizeGB: 11.0,
    license: 'Apache 2.0',
    hf: 'https://huggingface.co/Wan-AI/Wan2.1-VACE-14B',
    macRecommended: true,
    notes: 'Video editing variant. Mask + identity-preserving edits.',
  },
  {
    id: 'cogvideox-5b',
    name: 'CogVideoX-5B',
    modality: 'video',
    family: 'CogVideoX',
    dtype: 'bf16',
    sizeGB: 11.0,
    license: 'CogVideoX',
    hf: 'https://huggingface.co/THUDM/CogVideoX-5b',
    macRecommended: false,
    notes: 'Slower on Mac than LTX. Use GGUF mirror if available.',
  },
  {
    id: 'mochi-1',
    name: 'Mochi 1',
    modality: 'video',
    family: 'Mochi',
    dtype: 'bf16',
    sizeGB: 22.0,
    license: 'Apache 2.0',
    hf: 'https://huggingface.co/genmo/mochi-1-preview',
    macRecommended: false,
    notes: 'Tight on 24 GB. Prefer LTX/Hunyuan-GGUF on Mac.',
  },
  {
    id: 'svd-xt',
    name: 'Stable Video Diffusion XT',
    modality: 'video',
    family: 'SVD',
    dtype: 'fp16',
    sizeGB: 9.6,
    license: 'Stability AI Community',
    hf: 'https://huggingface.co/stabilityai/stable-video-diffusion-img2vid-xt',
    macRecommended: true,
    notes: 'Image-to-video, 25 frames. Older but Mac-stable.',
  },
  {
    id: 'animatediff-v3',
    name: 'AnimateDiff v3 SDXL',
    modality: 'video',
    family: 'AnimateDiff',
    dtype: 'fp16',
    sizeGB: 1.7,
    license: 'CreativeML OpenRAIL-M',
    hf: 'https://huggingface.co/guoyww/animatediff',
    macRecommended: true,
    notes: 'Motion module attached to SDXL base. Light footprint.',
  },
  {
    id: 'rife-49',
    name: 'RIFE 4.9',
    modality: 'video',
    family: 'Frame interpolation',
    dtype: 'fp16',
    sizeGB: 0.1,
    license: 'MIT',
    hf: 'https://huggingface.co/AlexWortega/RIFE',
    macRecommended: true,
    notes: 'Frame interpolation 8→24/30/48 fps. Fast on MPS.',
  },
]
