/** Voice / TTS models. Mac-friendly. */
export default [
  {
    id: 'f5-tts',
    name: 'F5-TTS',
    modality: 'voice',
    family: 'F5-TTS',
    dtype: 'fp16',
    sizeGB: 1.4,
    license: 'CC-BY-NC-4.0',
    hf: 'https://huggingface.co/SWivid/F5-TTS',
    macRecommended: true,
    notes: 'Zero-shot voice cloning from ~10s sample. Excellent on MPS.',
  },
  {
    id: 'xtts-v2',
    name: 'XTTS-v2 (Coqui)',
    modality: 'voice',
    family: 'XTTS',
    dtype: 'fp16',
    sizeGB: 1.9,
    license: 'CPML',
    hf: 'https://huggingface.co/coqui/XTTS-v2',
    macRecommended: true,
    notes: 'Multi-lingual zero-shot cloning.',
  },
  {
    id: 'gpt-sovits',
    name: 'GPT-SoVITS v2',
    modality: 'voice',
    family: 'SoVITS',
    dtype: 'fp16',
    sizeGB: 2.5,
    license: 'MIT',
    hf: 'https://huggingface.co/lj1995/GPT-SoVITS',
    macRecommended: true,
    notes: 'Few-shot fine-tune in minutes. Strong cloning quality.',
  },
  {
    id: 'kokoro-tts',
    name: 'Kokoro-TTS',
    modality: 'voice',
    family: 'Kokoro',
    dtype: 'fp16',
    sizeGB: 0.4,
    license: 'Apache 2.0',
    hf: 'https://huggingface.co/hexgrad/Kokoro-82M',
    macRecommended: true,
    notes: 'Tiny, fast, high-quality stock voices. No cloning.',
  },
  {
    id: 'chattts',
    name: 'ChatTTS',
    modality: 'voice',
    family: 'ChatTTS',
    dtype: 'fp16',
    sizeGB: 1.1,
    license: 'CC-BY-NC-4.0',
    hf: 'https://huggingface.co/2Noise/ChatTTS',
    macRecommended: true,
    notes: 'Conversational TTS with prosody. Non-commercial.',
  },
  {
    id: 'rvc-v2',
    name: 'RVC v2',
    modality: 'voice',
    family: 'RVC',
    dtype: 'fp16',
    sizeGB: 1.0,
    license: 'MIT',
    hf: 'https://huggingface.co/lengyue233/rvc-models',
    macRecommended: true,
    notes: 'Voice-conversion (any-to-target). Train your voice in ~1h on M5.',
  },
  {
    id: 'openvoice-v2',
    name: 'OpenVoice v2',
    modality: 'voice',
    family: 'OpenVoice',
    dtype: 'fp16',
    sizeGB: 0.8,
    license: 'MIT',
    hf: 'https://huggingface.co/myshell-ai/OpenVoiceV2',
    macRecommended: true,
    notes: 'Reference + style transfer. Light footprint.',
  },
  {
    id: 'whisper-large-v3',
    name: 'Whisper Large v3',
    modality: 'voice',
    family: 'Whisper',
    dtype: 'fp16',
    sizeGB: 3.1,
    license: 'MIT',
    hf: 'https://huggingface.co/openai/whisper-large-v3',
    macRecommended: true,
    notes: 'STT for transcribing your training data and captions.',
  },
]
