import NoteBlock from '../../../components/content/NoteBlock.jsx'

export default function S2C2pa() {
  return (
    <>
      <p>
        C2PA (Coalition for Content Provenance and Authenticity) is the cryptographic
        provenance standard for AI-generated media. Sign your AI Reels with C2PA so platforms can
        identify them as AI-generated and viewers can verify origin.
      </p>

      <h2>What C2PA does</h2>
      <ul>
        <li>Embeds signed metadata in the file: who created it, what tools were used, when.</li>
        <li>Cryptographically signed so it can't be forged.</li>
        <li>Platforms (Instagram, X, YouTube) read C2PA and label content accordingly.</li>
        <li>Viewers can inspect provenance.</li>
      </ul>

      <h2>Why bother</h2>
      <ul>
        <li>Honesty — your viewers know it's AI clone, not deepfake.</li>
        <li>Future-proofing — platforms increasingly require provenance for AI content.</li>
        <li>Legal cover — clear authorship trail.</li>
      </ul>

      <h2>Tools</h2>
      <ul>
        <li><code>c2patool</code> — Adobe's open-source CLI for adding C2PA manifests.</li>
        <li><code>truepic-tools</code> — alternative.</li>
        <li>Some camera apps (iPhone) and AI tools (Adobe Firefly) embed C2PA automatically.</li>
      </ul>

      <h2>Adding C2PA to ffmpeg output</h2>
      <p>
        After ffmpeg export, run c2patool to embed the manifest. The manifest declares "this file
        is AI-generated by [your tools] on [date]".
      </p>

      <h2>The Phase 5 / 7 capstone usage</h2>
      <p>
        For the AI clone capstone, default to embedding C2PA. Builds trust with audience; aligns
        with emerging platform requirements; legitimizes the work.
      </p>

      <NoteBlock title="The disclosure principle">
        Be honest that your AI clone content is AI-generated. Watermarks + C2PA + caption
        disclosure ("AI-generated character of myself") are responsible practice. The Phase 5b /
        Subject 27h responsible-use checklist applies.
      </NoteBlock>
    </>
  )
}
